services:
  worker:
    image: openledgerhub/worker:1.0.0
    container_name: opl_worker
    restart: always
    ports:
      - "8080:8080"
      - "5555:5555"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./keystore/keystore.json:/app/keystore.json
      - /etc/machine-id:/etc/machine-id:ro
    env_file:
      - .env
    networks:
      - worker-network

  scraper:
    image: openledgerhub/scraper:1.0.0
    container_name: opl_scraper
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - worker-network
    depends_on:
      - worker

networks:
  worker-network:
    driver: bridge
